name: CI/CD

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: prgma/payment
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata
        id: meta
        run: echo "tag=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/Payment 
          file: ./src/Payment/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}

  redeploy_railway:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy Production on Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_ENV_ID: ${{ secrets.RAILWAY_ENV_ID }}
        run: |
          set -e
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-7)
          cat > payload.json <<JSON
          {
            "query": "mutation ServiceInstanceUpdateImage(\$environmentId:String!, \$serviceId:String!, \$image:String!){ serviceInstanceUpdateImage(environmentId:\$environmentId, serviceId:\$serviceId, image:\$image) }",
            "variables": {
              "environmentId": "${RAILWAY_ENV_ID}",
              "serviceId": "${RAILWAY_SERVICE_ID}",
              "image": "prgma/payment:${IMAGE_TAG}"
            }
          }
          JSON
          curl -sS -X POST https://backboard.railway.com/graphql/v2 \
            -H "Authorization: Bearer ${RAILWAY_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data @payload.json | tee /dev/stderr
